#:schema node_modules/wrangler/config-schema.json
name = "taskmanagerpwa"
main = "src/worker.js"
compatibility_date = "2024-04-03"
[vars]
GOOGLE_CLIENT_ID = "365692313483-g4tv5i5agl4egs67h980vn6ce977p7df.apps.googleusercontent.com"

[ai]
binding = "AI"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "task-manager-db"
database_id = "ab97960a-23e8-4ee6-b2f2-9821d33450d6"
